### PR TITLE
Replace Vortice with Silk for Direct3D

### PR DESCRIPTION
**Pull request by skyebird189**
This PR replaces Vortice.Windows with Silk.NET for Direct3D.

### CODE REVIEW

**Comment by MrScautHD** [comment]
amazing work!

**Comment by amerkoleci** [comment]
Why that? Whats wrong with vortice? I would like know so I can improve it in case

**Comment by skyebird189** [comment]
I try to depend on as few things as possible - as such I am trying to make Silk.NET pretty much the only dependency.

That is the only reason, I much prefer Vortice in every other way (silk has a *huge* problem with causing my IDE to grind to a halt), and if I can't get silk working then I will continue to use Vortice.

Nothing wrong with Vortice at all, just my obsession with having as few dependencies as possible :)

**Comment by skyebird189** [comment]
I should add that I am not 100% sure I actually want to go ahead with this PR which is why I am not making these changes in the main branch.

**Comment by amerkoleci** [comment]
I see, thanks for feedback:)
Just to let you know I have also low level unsafe directx bindings https://github.com/amerkoleci/Vortice.Win32

**Comment by skyebird189** [comment]
Passes the texture test (aka the only actual functioning test), so I say it's good to go. Will test with Easel to make sure it properly works but it's good enough to merge.

**Comment by MrScautHD** [comment]
Amazing work

**Pull request merged**
